In [1]:
import tensorrt
import tensorflow as tf

2023-06-08 23:34:50.445064: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


# Tensors and operations

In [30]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [5]:
display(t.shape)
display(t.dtype)

TensorShape([2, 3])

tf.float32

In [11]:
display(t[:, 1:])
display(t[..., 1, tf.newaxis])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [12]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [14]:
t @ tf.transpose(t)

2023-06-08 23:41:45.613471: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [16]:
# Note the shape is empty
t2 = tf.constant(42)
display(t2)
display(t2.shape)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

TensorShape([])

# Tensors and Numpy

In [17]:
import numpy as np

In [35]:
a = np.array([2., 4., 5.])
print('Note: dtype=float64 is the default numpy but its unnecessary for most ANN! set dtype=tf.float32 manually!')
display(tf.constant(a, dtype=tf.float32))
display(t.numpy())
display(tf.square(a))
np.square(t)

Note: dtype=float64 is the default numpy but its unnecessary for most ANN! set dtype=tf.float32 manually!


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 5.], dtype=float32)>

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)