Use the Hugging Face Transformers library to download a pretrained language model capable of generating text (e.g., GPT), and try generating more convincing Shakespearean text. You will need to use the model’s generate() method—see Hugging Face’s documentation for more details.

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorrt
import tensorflow as tf
from transformers import TFOpenAIGPTLMHeadModel
from transformers import OpenAIGPTTokenizer

In [11]:
model = TFOpenAIGPTLMHeadModel.from_pretrained("openai-gpt")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFOpenAIGPTLMHeadModel: ['h.3.attn.bias', 'h.6.attn.bias', 'h.1.attn.bias', 'h.0.attn.bias', 'h.10.attn.bias', 'h.9.attn.bias', 'h.8.attn.bias', 'h.4.attn.bias', 'h.11.attn.bias', 'h.2.attn.bias', 'h.7.attn.bias', 'h.5.attn.bias']
- This IS expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFOpenAIGPTLMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predicti

In [2]:
tokenizer = OpenAIGPTTokenizer.from_pretrained("openai-gpt")

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [9]:
tokenizer("This royal")

{'input_ids': [616, 5751], 'attention_mask': [1, 1]}

In [6]:
prompt_text = "This royal throne of kings, this sceptred isle"
encoded_prompt = tokenizer.encode(prompt_text, add_special_tokens=False, return_tensors="tf")
encoded_prompt

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]], dtype=int32)>

In [12]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   498,   973, 32000,   980,  5705,   725,   488,   725,
         6560,   498,   246,  5908,   557,   618,   239,  1288,  7232,
        15969,   759,   808,  3725,   246, 18493,   498,   754, 23181,
          270,   488,   589,   525,   481,  1849,   618,   509,   817,
          485, 27790,   498,   544,   481],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   240,   488,   616, 16499,   240,   645,   507,  2864,
          551,   525,   249,   604,   595,  5476,  1311,  1295,   246,
         1796,   500,   481,  1030,   498,   481,  7232,  7339,   498,
          481,  1175,   498,   481,  2761,   240,   812,  4103,   664,
         4001,   562,   566,   620,  9500],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   645,   524,  7455,   626,   595, 18645,   240,
          487

In [13]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-" * 80)

this royal throne of kings, this sceptred isle of pidaria has proved more and more worthy of a hero as king. these mighty vessels can only carry a token of their achievement ; and all that the true king was able to boast of is the
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle, and this voyage, if it turns out that i have not thus far seen a change in the ways of the mighty kingdom of the men of the sea, will serve no purpose for one so defeated
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. if his empire did not yield, he would destroy his children. a crown would be required, but not a crown, not one of a king's. the promise of two kings could mean or
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle makes sense to me, you do not need to make a cla